/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BL.Users;
import BL.Stafi;
import DAL.UsersRepository;
import DAL.UsersException;
import DAL.StafiRepository;
import JBcrypt.BCrypt;
import javax.swing.JOptionPane;

/**
 *
 * @author dorron
 */
public class RegjistrimiUserWindow extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegjistrimiUserWindow
     */
    public RegjistrimiUserWindow() {
        initComponents();
    }
    
    public RegjistrimiUserWindow(Users uTemp){
        initComponents();
        this.uTemp = uTemp;
        perdoruesiComboBox.setSelectedItem(this.uTemp.getStafi());
        usernameTextField.setText(this.uTemp.getUsername());
    }
    
    //Objektet e instancura
    UsersRepository uR = new UsersRepository();
    Users uTemp;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        perdoruesiComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Regjistro Përdoruesin");

        jLabel1.setText("Përdoruesi:");

        perdoruesiComboBox.setModel(new javax.swing.DefaultComboBoxModel<Object>(new StafiRepository().findAll().toArray()));

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jButton1.setText("Ruaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(perdoruesiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordField)
                            .addComponent(usernameTextField))))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(perdoruesiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
           if(perdoruesiComboBox.getSelectedIndex() == -1 && usernameTextField.getText().equals("") || usernameTextField == null && passwordField == null){
                JOptionPane.showMessageDialog(this, "Nuk e keni mbushur asjnë opsion!","Gabim!",JOptionPane.ERROR_MESSAGE);
           }else if(perdoruesiComboBox.getSelectedIndex() == -1){
               JOptionPane.showMessageDialog(this, "Nuk e keni selektuar përdoruesin!","Gabim!",JOptionPane.ERROR_MESSAGE);
           }else if(usernameTextField.getText().equals("") || usernameTextField == null){
               JOptionPane.showMessageDialog(this, "Nuk e keni shkruar username!","Gabim!",JOptionPane.ERROR_MESSAGE);
           }else if(passwordField == null){
               JOptionPane.showMessageDialog(this, "Nuk e keni shkruar password!","Gabim!",JOptionPane.ERROR_MESSAGE);
           }else{
               Users u = new Users();
               Stafi s = (Stafi)perdoruesiComboBox.getSelectedItem();
               String username =usernameTextField.getText();
               String password = BCrypt.hashpw(new String(passwordField.getPassword()), BCrypt.gensalt(12));
               u.setStafi(s);
               u.setIDStafi(s.getIDStafi());
               u.setPasswordi(password);
               u.setUsername(username);
               if(uTemp != null){
                   uTemp.setPasswordi(password);
                   uTemp.setUsername(username);
                   uTemp.setIDStafi(s.getIDStafi());
                   uTemp.setStafi(s);
                   uR.edit(uTemp);
                   JOptionPane.showMessageDialog(this, "Përdoruesi u editua");
               }else{
                   uR.create(u);
                   JOptionPane.showMessageDialog(this, "Përdoruesi u krijua");
               }
           }
        }catch(UsersException ue){
            JOptionPane.showMessageDialog(this, ue.getMessage(),"Gabim!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<Object> perdoruesiComboBox;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
